apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.40
    path: /srv/nfs_hdd/pihole-pvc
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dnsmasq-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.40
    path: /srv/nfs_hdd/dnsmasq-pvc
  storageClassName: ""