apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: docker-registry-ns
spec:
  ports:
    - name: http-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: docker-registry
